const projects = [
    {
        id: "proj-1",
        title: "Website Redesign",
        description: "Complete overhaul of the company website with new branding",
        status: "active" as const,
        progress: 75,
        members: [
            {name: "Farzad Asgari", initials: "FA"},
            {name: "Sarah Lee", initials: "SL"},
            {name: "Mike Johnson", initials: "MJ"},
        ],
        dueDate: "2025-06-12",
    },
    {
        id: "proj-2",
        title: "Mobile Application",
        description: "iOS and Android app for tracking tasks and projects",
        status: "active" as const,
        progress: 45,
        members: [
            {name: "Alice Smith", initials: "AS"},
            {name: "Farzad Asgari", initials: "FA"},
            {name: "John Doe", initials: "JD"},
            {name: "Mike Johnson", initials: "MJ"},
        ],
        dueDate: "2025-06-10",
    },
    {
        id: "proj-3",
        title: "Backend API Development",
        description: "RESTful API development for the new CRM system",
        status: "on-hold" as const,
        progress: 30,
        members: [
            {name: "Mike Johnson", initials: "MJ"},
            {name: "Tom Wilson", initials: "TW"},
        ],
        dueDate: "2025-06-08",
    },
    {
        id: "proj-4",
        title: "Marketing Campaign",
        description: "Q3 digital marketing campaign for product launch",
        status: "completed" as const,
        progress: 100,
        members: [
            {name: "Sarah Lee", initials: "SL"},
            {name: "Alice Smith", initials: "AS"},
        ],
        dueDate: "2025-06-06",
    },
    {
        id: "proj-5",
        title: "Customer Portal",
        description: "Self-service customer portal with account management",
        status: "active" as const,
        progress: 60,
        members: [
            {name: "Tom Wilson", initials: "TW"},
            {name: "John Doe", initials: "JD"},
            {name: "Sarah Lee", initials: "SL"},
            {name: "Farzad Asgari", initials: "FA"},
            {name: "Alice Smith", initials: "AS"},
        ],
        dueDate: "2025-06-04",
    },
    {
        id: "proj-6",
        title: "Internal Dashboard",
        description: "Analytics dashboard for internal teams",
        status: "active" as const,
        progress: 25,
        members: [
            {name: "Alice Smith", initials: "AS"},
            {name: "Farzad Asgari", initials: "FA"},
        ],
        dueDate: "2025-06-02",
    },
];